# Generated by Django 4.1.7 on 2023-05-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',)},
        ),
    ]
