# Generated by Django 4.1.6 on 2023-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_contactus_email_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=64)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
