# Generated by Django 4.1.6 on 2023-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Euro'), (2, 'Dollar'), (3, 'Sterling')], default=2),
        ),
    ]
